version: "3.8"
services:
  web:
    image: "gitlab/gitlab-ce:latest"
    container_name: "gitlab"
    restart: always
    #hostname: ${GITLAB_HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        #external_url '$GITLAB_EXTERNAL_URL'
        letsencrypt['enable'] = false
    ports:
      - "127.0.0.1:8980:80"
      - "127.0.0.1:8922:22"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
